"""Multi-Agent Research System in LangGraph.

This module demonstrates an advanced, production-grade multi-agent research workflow:
1. Supervisor Node: Analyzes the research topic and generates targeted search queries.
2. Dynamic Map-Reduce (Send API): Concurrently dispatches search worker tasks for each query.
3. Search Worker Nodes: Execute targeted research and gather findings in parallel.
4. Analyst Node: Synthesizes all gathered findings into coherent, structured insights.
5. Writer Node: Drafts a comprehensive research report based on the insights.
6. Evaluator Node: Critiques report quality with structured output, triggering revision loops if needed.
"""

import json
import operator
from typing import Literal
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from typing_extensions import TypedDict, Annotated

from langchain.chat_models import init_chat_model
from langchain_core.messages import (
    AIMessage,
    BaseMessage,
    HumanMessage,
    SystemMessage,
)
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from langgraph.types import Send

# Load environment variables (API keys, settings) from .env file
load_dotenv()

# Initialize primary deterministic LLM (temperature=0 for structured planning and evaluation)
model = init_chat_model(
    model_provider="google_genai", model="gemini-2.5-flash-lite", temperature=0
)

# Initialize creative LLM (temperature=0.7 for fluid report writing and synthesis)
creative_llm = init_chat_model(
    model_provider="google_genai", model="gemini-2.5-flash-lite", temperature=0.7
)


# ============================================================================
# State Schemas
# ============================================================================


class ResearchState(TypedDict):
    """Main state dictionary for the multi-agent research workflow.

    Attributes:
        messages: Conversation message history tracked via add_messages.
        topic: Target research topic provided by the user.
        search_queries: List of targeted search queries generated by the supervisor.
        findings: Consolidated list of research findings appended via operator.add.
        analysis: Synthesized analysis produced by the analyst node.
        report: Final formatted research report drafted by the writer node.
        quality_score: Numeric quality score (0.0 to 10.0) assigned by evaluator.
        quality_feedback: Constructive critique and feedback from evaluator.
        iteration: Counter tracking revision loop iterations.
    """

    messages: Annotated[list[BaseMessage], add_messages]
    topic: str
    search_queries: list[str]
    findings: Annotated[list[str], operator.add]
    analysis: str
    report: str
    quality_score: float
    quality_feedback: str
    iteration: int


class SearchTaskState(TypedDict):
    """Micro-state schema for individual worker tasks dispatched via the Send API.

    Attributes:
        search_query: The specific search query string assigned to this worker.
    """

    search_query: str


class QualityEvaluation(BaseModel):
    """Pydantic schema for structured evaluation output from the critique node."""

    score: float = Field(
        description="Quality score from 0.0 to 10.0 evaluating report completeness and depth."
    )
    feedback: str = Field(
        description="Detailed feedback and specific improvement suggestions if score < 8.0."
    )
    passed: bool = Field(
        description="True if report meets production standards (score >= 8.0), False otherwise."
    )


# ============================================================================
# Graph Nodes & Task Functions
# ============================================================================


def supervisor(state: ResearchState) -> dict:
    """Supervisor Node: Plans research by generating 3 targeted search queries.

    Args:
        state: Current ResearchState containing the research topic.

    Returns:
        Dict updating search_queries, messages, and initializing iteration counter.
    """
    topic = state.get("topic", "General Research Topic")
    current_iteration = state.get("iteration", 0)

    # Prompt the LLM to generate structured JSON search queries
    prompt = [
        SystemMessage(
            content=(
                "You are a Senior Research Supervisor. Given a research topic, generate exactly 3 specific, "
                "distinct search queries to cover different angles (technical, historical, future impact). "
                'Return ONLY a JSON array of strings, e.g. ["query 1", "query 2", "query 3"]. '
                "Do not include markdown formatting or extra text."
            )
        ),
        HumanMessage(content=f"Research Topic: {topic}"),
    ]

    response = model.invoke(prompt)

    # Safely extract text string from LLM response
    raw_text = (
        response.content if isinstance(response.content, str) else str(response.content)
    )

    # Clean markdown backticks if present
    cleaned_text = raw_text.replace("```json", "").replace("```", "").strip()

    try:
        queries = json.loads(cleaned_text)
        if not isinstance(queries, list):
            raise ValueError("Output is not a JSON list")
    except Exception:
        # Fallback query generation if JSON parsing fails
        queries = [
            f"{topic} overview and core principles",
            f"{topic} latest technological developments",
            f"{topic} practical applications and future challenges",
        ]

    print(f"\n📋 [SUPERVISOR] Generated {len(queries)} research queries for '{topic}':")
    for idx, q in enumerate(queries[:3], 1):
        print(f"   {idx}. {q}")

    return {
        "search_queries": queries[:3],
        "iteration": current_iteration + 1,
        "messages": [
            AIMessage(
                content=f"[SUPERVISOR]: Generated search queries: {queries[:3]}",
                name="supervisor",
            )
        ],
    }


def map_to_searches(state: ResearchState) -> list[Send]:
    """Conditional Edge Map Function: Dynamically dispatches Send objects for parallel worker execution.

    Args:
        state: ResearchState containing search_queries list.

    Returns:
        List of Send objects targeting the 'search_worker' node with individual SearchTaskState inputs.
    """
    queries = state.get("search_queries", [])
    print(
        f"\n🚀 [MAP-REDUCE] Dispatching {len(queries)} parallel search tasks via Send API..."
    )
    return [Send("search_worker", {"search_query": query}) for query in queries]


def search_worker(state: SearchTaskState) -> dict:
    """Worker Node: Executes an individual search query task in parallel.

    Args:
        state: Micro-state containing 'search_query'.

    Returns:
        Dict appending findings string to the global state's findings list.
    """
    query = state["search_query"]
    print(f" 🔍 [SEARCH WORKER] Investigating query: '{query}'")

    # Simulate search & gather structured information via LLM
    response = model.invoke(
        [
            SystemMessage(
                content=(
                    "You are an expert Research Worker. Gather key facts, statistics, and insights "
                    "for the provided search query. Provide a concise bulleted summary of 3 key findings."
                )
            ),
            HumanMessage(content=f"Search Query: {query}"),
        ]
    )

    finding_text = (
        response.content if isinstance(response.content, str) else str(response.content)
    )

    formatted_finding = f"### Query: {query}\n{finding_text}"

    return {"findings": [formatted_finding]}


def analyst(state: ResearchState) -> dict:
    """Analyst Node: Aggregates and synthesizes all parallel worker findings.

    Args:
        state: ResearchState containing accumulated findings list.

    Returns:
        Dict updating the state's 'analysis' string.
    """
    findings = state.get("findings", [])
    findings_combined = "\n\n".join(findings)

    print(f"\n🧠 [ANALYST] Synthesizing {len(findings)} collected research findings...")

    response = model.invoke(
        [
            SystemMessage(
                content=(
                    "You are a Principal Data Analyst. Review all collected research findings below. "
                    "Identify key themes, patterns, trade-offs, and critical insights. "
                    "Synthesize them into a structured analysis."
                )
            ),
            HumanMessage(
                content=f"Topic: {state['topic']}\n\nCollected Findings:\n{findings_combined}"
            ),
        ]
    )

    analysis_text = (
        response.content if isinstance(response.content, str) else str(response.content)
    )

    return {
        "analysis": analysis_text,
        "messages": [
            AIMessage(
                content="[ANALYST]: Completed synthesis of research findings.",
                name="analyst",
            )
        ],
    }


def writer(state: ResearchState) -> dict:
    """Writer Node: Drafts a comprehensive final research report based on analysis.

    Args:
        state: ResearchState containing topic, analysis, and optional evaluator feedback.

    Returns:
        Dict updating the 'report' string in state.
    """
    print(
        f"\n✍️  [WRITER] Drafting comprehensive research report (Iteration {state.get('iteration', 1)})..."
    )

    feedback_context = ""
    if state.get("quality_feedback"):
        feedback_context = (
            f"\n\nPrevious Evaluator Feedback to Address:\n{state['quality_feedback']}"
        )

    response = creative_llm.invoke(
        [
            SystemMessage(
                content=(
                    "You are a Science & Technology Journalist. Write a clear, well-structured research report "
                    "with Executive Summary, Key Insights, Technical Deep Dive, and Future Outlook. "
                    "Use clean Markdown with headings."
                )
            ),
            HumanMessage(
                content=(
                    f"Topic: {state['topic']}\n\n"
                    f"Analysis Context:\n{state.get('analysis', '')}"
                    f"{feedback_context}"
                )
            ),
        ]
    )

    report_text = (
        response.content if isinstance(response.content, str) else str(response.content)
    )

    return {
        "report": report_text,
        "messages": [
            AIMessage(
                content="[WRITER]: Drafted research report.",
                name="writer",
            )
        ],
    }


def evaluator(state: ResearchState) -> dict:
    """Evaluator Node: Evaluates report quality using structured Pydantic output.

    Args:
        state: ResearchState containing the report string.

    Returns:
        Dict updating quality_score and quality_feedback in state.
    """
    print("\n🔍 [EVALUATOR] Reviewing report quality against criteria...")

    evaluator_llm = model.with_structured_output(QualityEvaluation)

    evaluation = evaluator_llm.invoke(
        [
            SystemMessage(
                content=(
                    "You are a Peer Review Editor. Evaluate the research report on clarity, depth, "
                    "accuracy, and structure. Assign a score from 0.0 to 10.0."
                )
            ),
            HumanMessage(content=f"Report to review:\n{state.get('report', '')}"),
        ]
    )

    print(f"   Score: {evaluation.score}/10.0 | Passed: {evaluation.passed}")
    print(f"   Feedback: {evaluation.feedback}")

    return {
        "quality_score": evaluation.score,
        "quality_feedback": evaluation.feedback,
        "messages": [
            AIMessage(
                content=f"[EVALUATOR]: Score={evaluation.score}, Feedback={evaluation.feedback}",
                name="evaluator",
            )
        ],
    }


def should_revise(state: ResearchState) -> Literal["writer", "end"]:
    """Conditional Edge Router: Decides whether to revise the report or complete the workflow.

    Args:
        state: ResearchState containing quality_score and iteration count.

    Returns:
        'writer' to route back for revision, or 'end' to terminate workflow.
    """
    score = state.get("quality_score", 0.0)
    iteration = state.get("iteration", 1)
    max_iterations = 2

    # If score meets quality benchmark (>= 8.0) or max iterations reached, finish workflow
    if score >= 8.0 or iteration >= max_iterations:
        print(
            f"\n✅ [ROUTER] Finalizing report (Score: {score}/10, Iterations: {iteration})"
        )
        return "end"

    print(
        f"\n🔄 [ROUTER] Quality benchmark not met (Score: {score} < 8.0). Routing back to WRITER for revision."
    )
    return "writer"


# ============================================================================
# Graph Builder & Compilation
# ============================================================================


def create_research_system():
    """Builds and compiles the multi-agent research StateGraph workflow.

    Returns:
        CompiledStateGraph: Complete compiled research pipeline ready for invocation.
    """
    workflow = StateGraph(ResearchState)

    # 1. Add core process nodes
    workflow.add_node("supervisor", supervisor)
    workflow.add_node("search_worker", search_worker)
    workflow.add_node("analyst", analyst)
    workflow.add_node("writer", writer)
    workflow.add_node("evaluator", evaluator)

    # 2. Define workflow entry point
    workflow.add_edge(START, "supervisor")

    # 3. Add conditional map edge for parallel search execution via Send API
    workflow.add_conditional_edges("supervisor", map_to_searches, ["search_worker"])

    # 4. Reduce step: parallel workers automatically fan-in to analyst node
    workflow.add_edge("search_worker", "analyst")

    # 5. Sequential execution: Analyst -> Writer -> Evaluator
    workflow.add_edge("analyst", "writer")
    workflow.add_edge("writer", "evaluator")

    # 6. Quality feedback loop router edge
    workflow.add_conditional_edges(
        "evaluator",
        should_revise,
        {"writer": "writer", "end": END},
    )

    return workflow.compile()


# ============================================================================
# Execution Entry Point
# ============================================================================

if __name__ == "__main__":
    print("==========================================================")
    print(" Multi-Agent Autonomous Research System (LangGraph) ")
    print("==========================================================")

    # Initialize research workflow
    app = create_research_system()

    # Define research prompt
    topic_input = "Impact of Quantum Computing on Modern Cryptography"

    initial_state = {
        "topic": topic_input,
        "messages": [],
        "findings": [],
        "search_queries": [],
        "analysis": "",
        "report": "",
        "quality_score": 0.0,
        "quality_feedback": "",
        "iteration": 0,
    }

    # Execute workflow graph
    final_output = app.invoke(initial_state)

    print("\n==========================================================")
    print(" FINAL GENERATED RESEARCH REPORT ")
    print("==========================================================")
    print(final_output["report"])
    print(f"\nFinal Quality Score: {final_output['quality_score']}/10.0")
